# 100 numpy exercises (Optional)

Source: https://github.com/rougier/numpy-100


#### How to run this notebook

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

#### How to get help

If you are stuck, you can ask for help on the community forum: https://jovian.ml/forum/t/100-numpy-exercises-hints-discussions-help/10561 . You can get help with errors, ask for hints, and share your solutions with others.

If you're new to Numpy, check out this notebook for a quick tutorial: https://jovian.ml/aakashns/python-numerical-computing-with-numpy


#### Saving your work

Remember to save a snapshot of your work from time to time using to your Jovian.ml account.

In [1]:
!pip install jovian --upgrade --quiet

In [2]:
import jovian

In [3]:
jovian.commit(project='100-numpy-exercises')

<IPython.core.display.Javascript object>

[jovian] Updating notebook "khadaake/100-numpy-exercises" on https://jovian.com
[jovian] Committed successfully! https://jovian.com/khadaake/100-numpy-exercises


'https://jovian.com/khadaake/100-numpy-exercises'

`jovian.commit` uploads the notebook to your Jovian.ml account, captures the Python environment and creates a shareable link for your notebook as shown above. You can use this link to share your work and let anyone (including you) run your notebooks and reproduce your work. Learn more: https://jovian.ml/docs/


In [5]:
# Ucomment the next line if you need install numpy
!pip install numpy --upgrade

     |████████████████████████████████| 17.3 MB 6.7 MB/s            
  Attempting uninstall: numpy
    Found existing installation: numpy 1.20.3
    Uninstalling numpy-1.20.3:
      Successfully uninstalled numpy-1.20.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
scipy 1.7.2 requires numpy<1.23.0,>=1.16.5, but you have numpy 1.24.3 which is incompatible.
numba 0.54.1 requires numpy<1.21,>=1.17, but you have numpy 1.24.3 which is incompatible.


#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [10]:
np.version.version

'1.24.3'

#### 3. Create a null vector of size 10 (★☆☆)

In [12]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [15]:
np.array([1, 2, 3, 4, 5]).nbytes

40

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [16]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [21]:
null_vec = np.zeros(10)
null_vec[4] = 1
print(null_vec)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [17]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [24]:
arr = np.array([1, 2, 3, 4, 5])
reversed_arr = arr[::-1]
print(reversed_arr)

[5 4 3 2 1]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [25]:
np.arange(0, 9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [27]:
arr = np.array([1, 2, 0, 0, 4, 0])
print(np.nonzero(arr))

(array([0, 1, 4]),)


Save your progress by commiting your work to Jovian

In [28]:
import jovian

In [29]:
jovian.commit(project='numpy-100-exercises')

<IPython.core.display.Javascript object>

[jovian] Creating a new project "khadaake/numpy-100-exercises"
[jovian] Committed successfully! https://jovian.com/khadaake/numpy-100-exercises


'https://jovian.com/khadaake/numpy-100-exercises'

#### 11. Create a 3x3 identity matrix (★☆☆)

In [30]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [31]:
np.random.rand(3, 3, 3)

array([[[0.08739264, 0.96217425, 0.98277431],
        [0.41665922, 0.63598569, 0.77415512],
        [0.9167799 , 0.46291206, 0.62627091]],

       [[0.78406163, 0.92507364, 0.69820442],
        [0.00371425, 0.34983018, 0.24621602],
        [0.59073559, 0.00749722, 0.40730388]],

       [[0.45737335, 0.37577552, 0.2411504 ],
        [0.47277807, 0.33245475, 0.41730896],
        [0.24704943, 0.45989885, 0.01462317]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [34]:
arr = np.random.rand(10, 10)
print(arr.min(), arr.max(), sep='\n')

0.003210634342319829
0.9946355942120624


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [35]:
np.random.rand(30).mean()

0.390181090582635

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [40]:
arr = np.ones((5, 5))
arr[1:-1, 1:-1] = 0
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [41]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

padded_arr = np.pad(arr, pad_width=1, mode='constant', constant_values=0)

print(padded_arr)

[[0 0 0 0 0]
 [0 1 2 3 0]
 [0 4 5 6 0]
 [0 7 8 9 0]
 [0 0 0 0 0]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
nan
False
False
nan
True
False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [43]:
arr = np.zeros((5, 5))
np.fill_diagonal(arr[1:], [1, 2, 3, 4])
print(arr)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [48]:
mat = np.zeros((8, 8), dtype=int)

arr[::2, 1::2] = 1
arr[1::2, ::2] = 1

print(arr)

[[0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [50]:
arr = np.zeros((6, 7, 8))

linear_index = 100
x, y, z = np.unravel_index(linear_index, arr.shape)
print(x, y, z)

1 5 4


Save your progress by commiting your work to Jovian

In [7]:
import jovian

In [51]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "khadaake/numpy-100-exercises" on https://jovian.com
[jovian] Committed successfully! https://jovian.com/khadaake/numpy-100-exercises


'https://jovian.com/khadaake/numpy-100-exercises'

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [12]:
a = np.array([[0, 1], [1, 0]])
np.tile(a, (4, 4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [23]:
a = np.random.rand(5, 5)
normalized_a = (a - np.min(a)) / (np.max(a) - np.min(a))
print(normalized_a)



[[0.46419693 0.79170379 0.30774439 0.59635775 0.23061222]
 [0.52174196 0.77364748 0.32226445 0.11585886 0.78561523]
 [0.         0.95660815 0.70476024 0.61233988 0.0415267 ]
 [0.50572608 0.7559616  1.         0.70427447 0.32931347]
 [0.51168246 0.39648806 0.63153305 0.35474716 0.85861218]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [24]:
rgba_dtype = np.dtype([('R', np.uint8), ('G', np.uint8), ('B', np.uint8), ('A', np.uint8)])

colors = np.array([(255, 0, 0, 255), (0, 255, 0, 255), (0, 0, 255, 255)], dtype=rgba_dtype)

print(colors)


[(255,   0,   0, 255) (  0, 255,   0, 255) (  0,   0, 255, 255)]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [36]:
a = np.array([[2, 4, 5],
            [4, 3, 2],
            [6, 9, 12],
            [3, 9, 2],
            [2, 3, 7]])
b = np.array([[4, 3],
            [5, 8],
            [4, 3]])
np.matmul(a, b)

array([[ 48,  53],
       [ 39,  42],
       [117, 126],
       [ 65,  87],
       [ 51,  51]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [38]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
negate = (a > 3) & (a < 8)
a[negate] *= -1
print(a)

[ 1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [41]:
9
10

10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [42]:
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1

NameError: name 'Z' is not defined

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [49]:
nan
0
array([-9.22337204e+18])

array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

In [52]:
a = np.array([-2.4, -1.7, 0.0, 1.7, 2.4])
a_rounded = np.copysign(np.ceil(np.abs(a)), a)
print(a_rounded)

[-3. -2.  0.  2.  3.]


#### 30. How to find common values between two arrays? (★☆☆)

In [53]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
b = np.array([3, 4, 8, 10])
np.intersect1d(a, b)

array([3, 4, 8])

Save your progress by commiting your work to Jovian

In [8]:
import jovian

In [54]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "khadaake/numpy-100-exercises" on https://jovian.com
[jovian] Committed successfully! https://jovian.com/khadaake/numpy-100-exercises


'https://jovian.com/khadaake/numpy-100-exercises'

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [55]:
np.seterr(all="ignore")

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [60]:
False

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [61]:
today = np.datetime64('today', 'D')

yesterday = today - np.timedelta64(1, 'D')
tomorrow = today + np.timedelta64(1, 'D')

print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)


Yesterday: 2023-05-15
Today: 2023-05-16
Tomorrow: 2023-05-17


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [62]:
start_date = np.datetime64('2016-07-01')
end_date = np.datetime64('2016-08-01')

dates = np.arange(start_date, end_date, np.timedelta64(1, 'D'))

for date in dates:
    print(date)

2016-07-01
2016-07-02
2016-07-03
2016-07-04
2016-07-05
2016-07-06
2016-07-07
2016-07-08
2016-07-09
2016-07-10
2016-07-11
2016-07-12
2016-07-13
2016-07-14
2016-07-15
2016-07-16
2016-07-17
2016-07-18
2016-07-19
2016-07-20
2016-07-21
2016-07-22
2016-07-23
2016-07-24
2016-07-25
2016-07-26
2016-07-27
2016-07-28
2016-07-29
2016-07-30
2016-07-31


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [65]:
A = np.array([1, 2, 3], dtype=float)
B = np.array([4, 5, 6])

A += B
A *= (-A/2)

print(A)

[-12.5 -24.5 -40.5]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [72]:
a = np.random.rand(5) * 10
int_part1 = np.floor(a)
int_part2 = np.trunc(a)
int_part3 = a.astype(int)
int_part4 = np.int64(a)
print(int_part1, int_part2, int_part3, int_part4, sep='\n')

[5. 6. 7. 7. 4.]
[5. 6. 7. 7. 4.]
[5 6 7 7 4]
[5 6 7 7 4]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [74]:
a = np.arange(5).reshape(5, 1) + np.zeros((1, 5))
print(a)

[[0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [80]:
iterable = (i for i in range(10))
a = np.fromiter(iterable, dtype=int)

print(a)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [89]:
a = np.linspace(0.01, 0.99, 10)
print(a)
b = np.linspace(0,1,12,endpoint=True)[1:-1]
print(b)


[0.01       0.11888889 0.22777778 0.33666667 0.44555556 0.55444444
 0.66333333 0.77222222 0.88111111 0.99      ]
[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [95]:
a = np.random.rand(10)
np.sort(a)

array([0.20194637, 0.25763656, 0.35188911, 0.42150068, 0.43714775,
       0.77599059, 0.78225428, 0.83017576, 0.85413506, 0.89478894])

Save your progress by commiting your work to Jovian

In [10]:
import jovian

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

Save and commit your work.

In [12]:
import jovian

In [13]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-100-exercises" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-100-exercises


'https://jovian.ml/aakashns/numpy-100-exercises'

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

Save and commit your work.

In [14]:
import jovian

In [15]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-100-exercises" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-100-exercises


'https://jovian.ml/aakashns/numpy-100-exercises'

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

Save and commit your work

In [16]:
import jovian

In [17]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-100-exercises" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-100-exercises


'https://jovian.ml/aakashns/numpy-100-exercises'

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

Save and commit your work.

In [18]:
import jovian

In [19]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-100-exercises" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-100-exercises


'https://jovian.ml/aakashns/numpy-100-exercises'

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

Save and commit your work

In [20]:
import jovian

In [21]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-100-exercises" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-100-exercises


'https://jovian.ml/aakashns/numpy-100-exercises'

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

Save and commit your work

In [22]:
import jovian

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..


Congratulations on completing the 100 exercises, well done!

#### What to do next?

- Share your completed notebook on Facebook, LinkedIn or Twitter and challenge your friends.
- Share your solutions and help others on the forum: https://jovian.ml/forum/t/100-numpy-exercises-hints-discussions-help/10561
- Check out our course on "Data Analysis with Python: Zero to Pandas" - https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas
- Star this repository to show your appreciation for the original author of this notebook: https://github.com/rougier/numpy-100